### ISSUE TITLE
Sharing secret between JS and C#

### ISSUE THREAD

**Issue by acymiranda** [therightstuff/simple-free-encryption-tool#59]
Hi Adam,

Great project, many thanks for your hours and effort on this!

However, I have a question and even looking in many many sites over the internet, I couldn't find a solution for that. You are creating an encrypted text in JS using some secret, right? And then, you'll need to send this encrypted text to C# to be decrypted and for that you will need the same secret used in JS, right? How could that be achieved?

Because if I hardcoded the secret in JS, anyone could see the source-code of my site and see the secret. If I generate a random secret, how C# will know this random secret (that was generated in JS)? Unless you send the secret via Ajax (which would be my case).

Many many thanks! :-)

**Comment by therightstuff** [comment]
Hi @acymiranda ! 

> And then, you'll need to send this encrypted text to C# to be decrypted and for that you will need the same secret used in JS, right? How could that be achieved?

Absolutely correct. The crucial thing here is NEVER to hardcode your secret, or store it anywhere within your solution. I handled this in two ways:

1. The initial secret required to establish a secure channel (by exchanging public RSA keys) is generated by the server and emailed to the user. If the communication is over a secure channel already (eg. HTTPS/SSL) there's no need for additional protection for the public keys and they can simply be transmitted directly.
|
2. Each message is encrypted with AES using its own randomly generated secret, and the secret itself is encrypted using the RSA public keys and sent along with the encrypted message. In this way, only the intended recipient will have the ability to decrypt the message secret and can use the decrypted message secret to decrypt the message

**Comment by therightstuff** [comment]
Hi @acymiranda , do you need anything further or can I close this issue?

**Comment by acymiranda** [comment]
Hi Adam, sorry for forgetting to reply your comments about my question :-( 

Yes, you can close it, many many thanks!

**Comment by therightstuff** [comment]
No worries, feel free to open more if you need :)
